### ISSUE TITLE
Missing files on Build and preview

### ISSUE THREAD

**Issue by newaeonweb** [p-j/generator-yawa#6]
The following files are missing after build:
127.0.0.1/:231 GET http://127.0.0.1:9000/bower_components/groundwork/js/plugins/jquery-tooltip.js 
127.0.0.1/:233 GET http://127.0.0.1:9000/bower_components/groundwork/js/components/disabled.js 
(index):238 GET http://127.0.0.1:9000/bower_components/groundwork/js/components/modals.js 
(index):239 GET http://127.0.0.1:9000/bower_components/groundwork/js/components/pagination.js 
(index):241 GET http://127.0.0.1:9000/bower_components/groundwork/js/components/tiles.js 
(index):242 GET http://127.0.0.1:9000/bower_components/groundwork/js/components/tooltips.js 

maybe the generator don't copy them to components folder

**Comment by p-j** [comment]
Sorry, just saw your issue.
I'll have a look at it either tonight or some time in the weekend, I wont have time before.

Can you tell which options did you select ? (requireJS, Groundwork, assemble ?)

Thanks for reporting!

**Comment by p-j** [comment]
Sorry, I've been very busy the past few days. Hopefully I can have a look a it sometime this week.

**Comment by p-j** [comment]
Sorry for the delay.

It's been fixed just now. You can `npm update -g generator-yawa` to get a more up to date version.
If you get a SASS error when you run your project that looks like this : 
```
error app/styles/main.scss (Line 71 of app/bower_components/groundwork/src/sass/base/_grid.sass: List index 0 must be a non-zero integer for `nth')
```

Please apply the fix provided in [this unmerge pull request](https://github.com/groundworkcss/groundwork/pull/268). You may let @ghepting (Groundwork's author) know that you'd like him to merge it and publish a fixed version as well. ;-)
