### ISSUE TITLE
grunt build failure

### ISSUE THREAD

**Issue by bronzelegs** [p-j/generator-yawa#7]
Error: ENOENT, no such file or directory '/Users/tdavis/Web/yawa/.tmp/bower_components/jquery/jquery.js'

Not sure what changed, used in Jan for a webapp, this week no joy

**Comment by p-j** [comment]
Mhm, probably the jquery package on bower has changed its internal organization and the jquery.js is not a the root anymore.

It's an easy fix, you can go to bower_components/jquery and see whats wrong and update your gruntfile accordingly.

I'll make an update later this week with the fix.

Thanks for noticing.

**Comment by bronzelegs** [comment]
well the correct path is /Users/tdavis/Web/yawa/.tmp/bower_components/jquery/dist/jquery.js presumably

why did this get wonky?

**Comment by p-j** [comment]
I think this should fix it : https://github.com/p-j/generator-yawa/pull/8 

Unfortunately I cannot test it right now, I'll have to do it later this week as I don't have my setup ready for that right now.
